module.exports = {
    globDirectory: "./",
    globPatterns: ["**/*.{wav,mp3,WAV,gif,png,webp,otf,jpg,js,json,css,html}"],
    swDest: "sw.js",
    swSrc: "dist/sw.js",
    globIgnores:[
        "dist/index.html",
        "BookContent/**/*", 
        "interactive-book-static/**/*",
        "GDLBookContent/**/*",
        "node_modules/**/*",
        "workbox-config.js",
        "sw-src.ts",
        "dist/sw.js",
        "tsconfig.json",
        "webpack.config.js",
        "package.json",
        "package-lock.json",
        "README.md",
    ],
};
